image: registry.gitlab.com/potpourri1/hublabbot

stages:
  - commit-lint
  - code-lint
  - deploy-docs

commit-lint:
  stage: commit-lint
  interruptible: true
  script:
    - git fetch origin master:master --depth 50
    - commit-lint

style-lint:
  stage: code-lint
  interruptible: true
  script: style-lint
  rules:
    - changes:
      - hublabbot/**/*.py
      - setup.{py,cfg}
      - tools/style-lint
      - tools/cfg/flake8-mypy.ini
      - tools/cfg/cspell.json

static-analysis:
  stage: code-lint
  interruptible: true
  script: static-analysis
  rules:
    - changes:
      - hublabbot/**/*.py
      - typeshed/**/*.pyi
      - setup.{py,cfg}
      - tools/static-analysis
      - tools/cfg/jscpd.json

pages:
  stage: deploy-docs
  interruptible: true
  script: build-docs
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
      - hublabbot/**/*.py
      - tools/build-docs
      - tools/cfg/pdoc3/*
